//! 「上下文生产者」的字段元数据表：`[soul]`（人格）与 `[memory]`（记忆）。
//!
//! 拆出本文件的唯一原因见 `AGENTS.md` §5.10（文件规模约定）：`fields.rs` 已 ~450 行，
//! 再塞 30+ 条字段会顶到 600 行上限。表本身与 `fields.rs` 同构，由
//! `registry::capability_common_fields()` 合并后交给 `schema_json()`。
//!
//! ⚠️ 这些是**元数据**：真实默认值仍在各 serde `default_*()` 里（单一权威）。
//! 漂移由 `registry/tests.rs` 的 `field_keys_exist_in_config` 兜底。

use super::{Capability, FieldKind, FieldSchema, HotReload};

/// `[memory]` 顶层字段（路径 `["memory"]`）。
pub(super) const MEMORY_FIELDS: &[FieldSchema] = &[
    FieldSchema {
        key: "enabled",
        label: "启用记忆",
        kind: FieldKind::Bool,
        default_hint: "false",
        help: "关闭时零依赖零成本（行为与加记忆之前完全一致）；打开后本轮对话会写入本地 SQLite。",
        hot: HotReload::NextSession,
        required: true,
    },
    FieldSchema {
        key: "engine",
        label: "引擎",
        kind: FieldKind::Enum(&["graph", "none"]),
        default_hint: "graph",
        help: "graph = 内置图记忆（本地词法召回，零外网调用）；none = 保留配置但不生效（旧键 backend 仍可读）。",
        hot: HotReload::NextSession,
        required: true,
    },
    FieldSchema {
        key: "db_path",
        label: "库文件路径",
        kind: FieldKind::Path,
        default_hint: "/data/memory.db",
        help: "⚠️ 必须放在挂载卷内，否则重建容器即丢全部记忆。",
        hot: HotReload::NextSession,
        required: true,
    },
    FieldSchema {
        key: "db_busy_timeout_ms",
        label: "SQLite 写锁等待(ms)",
        kind: FieldKind::Int,
        default_hint: "5000",
        help: "与 DSH 桌面端共用同一个库文件时才需要调大（两进程写同一文件）。",
        hot: HotReload::NextSession,
        required: false,
    },
    FieldSchema {
        key: "recall_enabled",
        label: "启用召回",
        kind: FieldKind::Bool,
        default_hint: "true",
        help: "关掉 = 只写不读（先积累数据，之后再打开观察效果）。",
        hot: HotReload::NextSession,
        required: false,
    },
    FieldSchema {
        key: "extraction_enabled",
        label: "启用抽取",
        kind: FieldKind::Bool,
        default_hint: "true",
        help: "关掉 = 只存原文、不调用辅助模型，因此没有摘要可召回。",
        hot: HotReload::NextSession,
        required: false,
    },
    FieldSchema {
        key: "fresh_turn_count",
        label: "近况轮数",
        kind: FieldKind::Int,
        default_hint: "5",
        help: "最近这几轮的原文已在会话上下文里，不再重复召回（省 token）。",
        hot: HotReload::NextSession,
        required: false,
    },
    FieldSchema {
        key: "recall_max_nodes",
        label: "每次最多召回条数",
        kind: FieldKind::Int,
        default_hint: "6",
        help: "召回太多会挤压其余上下文；语音场景 4~6 条通常够用。",
        hot: HotReload::NextSession,
        required: false,
    },
    FieldSchema {
        key: "recall_max_tokens",
        label: "注入 token 预算",
        kind: FieldKind::Int,
        default_hint: "400",
        help: "注入正文的硬上限（中文按约 1 token/字估算）；超预算先丢证据原文、再丢摘要。",
        hot: HotReload::NextSession,
        required: false,
    },
    FieldSchema {
        key: "recall_budget_ms",
        label: "召回耗时预算(ms)",
        kind: FieldKind::Int,
        default_hint: "300",
        help: "关键路径预算：超时立即按「无记忆」继续，绝不让记忆拖慢首字延迟。",
        hot: HotReload::NextSession,
        required: false,
    },
    FieldSchema {
        key: "maintenance_interval",
        label: "维护间隔(轮)",
        kind: FieldKind::Int,
        default_hint: "6",
        help: "每 N 轮做一次保留策略与隔离重试（后台执行，不占关键路径）。",
        hot: HotReload::NextSession,
        required: false,
    },
    FieldSchema {
        key: "inject_position",
        label: "注入位置",
        kind: FieldKind::Enum(&["after_history", "before_history"]),
        default_hint: "after_history",
        help: "默认放在历史之后：保住「人格 + 历史」这段前缀的 prompt 缓存命中。",
        hot: HotReload::NextSession,
        required: false,
    },
    FieldSchema {
        key: "quarantine_max_attempts",
        label: "抽取最大尝试次数",
        kind: FieldKind::Int,
        default_hint: "3",
        help: "超过即永久隔离该轮（不再自动重试），可在记忆页「立即维护」里释放。",
        hot: HotReload::NextSession,
        required: false,
    },
    FieldSchema {
        key: "scope_prefix",
        label: "作用域前缀",
        kind: FieldKind::Str,
        default_hint: "xiaozhi",
        help: "记忆按 <前缀>:<设备号> 隔离；多台设备各记各的。",
        hot: HotReload::NextSession,
        required: false,
    },
];

/// `[memory.retention]`（路径 `["memory","retention"]`）。
pub(super) const MEMORY_RETENTION_FIELDS: &[FieldSchema] = &[
    FieldSchema {
        key: "keep",
        label: "原文保留策略",
        kind: FieldKind::Enum(&["all", "referenced", "recent"]),
        default_hint: "all",
        help: "all = 全部保留（默认，最安全）；referenced/recent 只删「没有被记忆引用」的原文（被引用的证据永不删）。",
        hot: HotReload::NextSession,
        required: false,
    },
    FieldSchema {
        key: "recent_turns",
        label: "保留最近轮数",
        kind: FieldKind::Int,
        default_hint: "0",
        help: "keep = \"recent\" 时生效：更早的未引用原文可删。",
        hot: HotReload::NextSession,
        required: false,
    },
    FieldSchema {
        key: "retention_days",
        label: "保留天数",
        kind: FieldKind::Int,
        default_hint: "0",
        help: "超过 N 天的未引用原文可删（0 = 不限）。",
        hot: HotReload::NextSession,
        required: false,
    },
    FieldSchema {
        key: "dry_run",
        label: "只演练不删除",
        kind: FieldKind::Bool,
        default_hint: "false",
        help: "先看清会删多少条再真正执行（日志与「立即维护」都会报数量）。",
        hot: HotReload::NextSession,
        required: false,
    },
];

/// `[memory.extractor]`（路径 `["memory","extractor"]`）。
pub(super) const MEMORY_EXTRACTOR_FIELDS: &[FieldSchema] = &[
    FieldSchema {
        key: "api_base",
        label: "抽取模型地址",
        kind: FieldKind::Str,
        default_hint: "（空 = 复用 [llm]）",
        help: "抽取是一次独立的模型调用，可以指向更便宜的端点；留空则复用 [llm]。",
        hot: HotReload::NextSession,
        required: false,
    },
    FieldSchema {
        key: "api_key",
        label: "抽取模型密钥",
        kind: FieldKind::Password,
        default_hint: "（空 = 复用 [llm]）",
        help: "留空不修改；GET /api/config 永不回传明文（只给 has_api_key）。",
        hot: HotReload::NextSession,
        required: false,
    },
    FieldSchema {
        key: "model",
        label: "抽取模型名",
        kind: FieldKind::Str,
        default_hint: "（空 = 复用 [llm]）",
        help: "建议用小模型（抽取只要稳定 JSON）。",
        hot: HotReload::NextSession,
        required: false,
    },
    FieldSchema {
        key: "temperature",
        label: "抽取温度",
        kind: FieldKind::Float,
        default_hint: "0.1",
        help: "抽取要稳定，不要发挥。",
        hot: HotReload::NextSession,
        required: false,
    },
];

/// `[soul]`（路径 `["soul"]`）。
pub(super) const SOUL_FIELDS: &[FieldSchema] = &[
    FieldSchema {
        key: "enabled",
        label: "启用人格档案",
        kind: FieldKind::Bool,
        default_hint: "false",
        help: "关闭时完全退回 [llm].system_prompt（逐字节一致，可随时回滚）。",
        hot: HotReload::NextSession,
        required: true,
    },
    FieldSchema {
        key: "name",
        label: "名字",
        kind: FieldKind::Str,
        default_hint: "小智",
        help: "自称；可在其他字段里用 {{name}} 引用。",
        hot: HotReload::NextSession,
        required: true,
    },
    FieldSchema {
        key: "self_intro",
        label: "自我定位",
        kind: FieldKind::Text,
        default_hint: "",
        help: "一段话：你是谁、在做什么。",
        hot: HotReload::NextSession,
        required: false,
    },
    FieldSchema {
        key: "form",
        label: "形象",
        kind: FieldKind::Str,
        default_hint: "",
        help: "如「一只住在音箱里的小狐狸」——影响自称与比喻方式。",
        hot: HotReload::NextSession,
        required: false,
    },
    FieldSchema {
        key: "age_feel",
        label: "年龄感",
        kind: FieldKind::Str,
        default_hint: "",
        help: "如「十来岁」。",
        hot: HotReload::NextSession,
        required: false,
    },
    FieldSchema {
        key: "worldview",
        label: "世界观",
        kind: FieldKind::Text,
        default_hint: "",
        help: "世界是什么样的（决定它怎么解释事情）。",
        hot: HotReload::NextSession,
        required: false,
    },
    FieldSchema {
        key: "backstory",
        label: "来历",
        kind: FieldKind::Text,
        default_hint: "",
        help: "背景故事：它是怎么来的、经历过什么。",
        hot: HotReload::NextSession,
        required: false,
    },
    FieldSchema {
        key: "relationship_origin",
        label: "与用户的关系起点",
        kind: FieldKind::Text,
        default_hint: "",
        help: "关系是怎么开始的，比「关系=朋友」更能锁定语气。",
        hot: HotReload::NextSession,
        required: false,
    },
    FieldSchema {
        key: "traits",
        label: "性格",
        kind: FieldKind::Text,
        default_hint: "",
        help: "每行一条「标签：遇到 X 会怎么做」——只写形容词会失效。",
        hot: HotReload::NextSession,
        required: false,
    },
    FieldSchema {
        key: "values",
        label: "价值",
        kind: FieldKind::Text,
        default_hint: "",
        help: "每行一条它坚持的东西。",
        hot: HotReload::NextSession,
        required: false,
    },
    FieldSchema {
        key: "boundaries",
        label: "红线/拒绝清单",
        kind: FieldKind::Text,
        default_hint: "",
        help: "每行一条不做的事（安全与一致性）。",
        hot: HotReload::NextSession,
        required: false,
    },
    FieldSchema {
        key: "tone",
        label: "语气",
        kind: FieldKind::Str,
        default_hint: "",
        help: "如「轻快、温和、带一点好奇」。",
        hot: HotReload::NextSession,
        required: false,
    },
    FieldSchema {
        key: "colloquial",
        label: "口语化",
        kind: FieldKind::Bool,
        default_hint: "true",
        help: "允许短句/省略主语，不要书面语。",
        hot: HotReload::NextSession,
        required: false,
    },
    FieldSchema {
        key: "address_user",
        label: "称呼用户",
        kind: FieldKind::Str,
        default_hint: "你",
        help: "可在其他字段里用 {{address_user}} 引用。",
        hot: HotReload::NextSession,
        required: false,
    },
    FieldSchema {
        key: "catchphrases",
        label: "口头禅",
        kind: FieldKind::Text,
        default_hint: "",
        help: "每行一条；提示里会声明「自然使用，不要每句都用」。",
        hot: HotReload::NextSession,
        required: false,
    },
    FieldSchema {
        key: "emoji",
        label: "允许 emoji",
        kind: FieldKind::Bool,
        default_hint: "false",
        help: "⚠️ 默认关：TTS 会把 emoji 念出来，属事故。",
        hot: HotReload::NextSession,
        required: false,
    },
    FieldSchema {
        key: "max_sentences",
        label: "最多句数",
        kind: FieldKind::Int,
        default_hint: "2",
        help: "写进平台约束的硬上限（1~8）。",
        hot: HotReload::NextSession,
        required: false,
    },
    FieldSchema {
        key: "max_chars",
        label: "最多字数",
        kind: FieldKind::Int,
        default_hint: "40",
        help: "写进平台约束的硬上限（10~500）。",
        hot: HotReload::NextSession,
        required: false,
    },
    FieldSchema {
        key: "scenario",
        label: "当前情境",
        kind: FieldKind::Text,
        default_hint: "",
        help: "如「书房里，晚上」。",
        hot: HotReload::NextSession,
        required: false,
    },
    FieldSchema {
        key: "device_hint",
        label: "设备提示",
        kind: FieldKind::Text,
        default_hint: "",
        help: "如「这是放在客厅的音箱」。",
        hot: HotReload::NextSession,
        required: false,
    },
    FieldSchema {
        key: "examples",
        label: "风格范例",
        kind: FieldKind::Text,
        default_hint: "",
        help: "每条一组 Q/A（如「用户：今天几度？ / 你：…」）——锁风格最有效的手段。",
        hot: HotReload::NextSession,
        required: false,
    },
];

/// 上下文生产者的公共字段表（与 `fields.rs` 的 `CAPABILITY_COMMON_FIELDS` 合并使用）。
pub(super) const CONTEXT_COMMON_FIELDS: &[(
    Capability,
    &'static [&'static str],
    &'static [FieldSchema],
)] = &[
    (Capability::Soul, &["soul"], SOUL_FIELDS),
    (Capability::Memory, &["memory"], MEMORY_FIELDS),
    (
        Capability::Memory,
        &["memory", "retention"],
        MEMORY_RETENTION_FIELDS,
    ),
    (
        Capability::Memory,
        &["memory", "extractor"],
        MEMORY_EXTRACTOR_FIELDS,
    ),
];
