//! 注册表的**字段元数据表**（能力公共字段 + 各实现私有字段）。
//!
//! 纯数据表：拆出原因见 `AGENTS.md` §5.10（文件规模约定）。这些常量是 `pub(super)`——
//! 只有同目录的 `mod.rs` / `impls.rs` 需要它们；对外仍经 `schema_json()` 投影。

use super::{Capability, FieldKind, FieldSchema, HotReload};

/// 能力级**公共**字段（跨实现共享，如 `[tts].engine` 选择器与 `cache_entries`）。
/// 键相对能力段（`["tts"]`），与实现的私有字段分开，避免同一字段在两个实现里重复声明。
///
/// P4 约定：每个能力都用 `engine` 选实现（值 = 描述符 id 去掉 `"<cap>."` 前缀）；
/// `[memory].engine` 的定义在 `fields_context.rs`（它是闭枚举 `graph|none`）。
pub(super) const CAPABILITY_COMMON_FIELDS: &[(
    Capability,
    &'static [&'static str],
    &'static [FieldSchema],
)] = &[
    (
        Capability::Asr,
        &["asr"],
        &[FieldSchema {
            key: "engine",
            label: "识别引擎",
            kind: FieldKind::Enum(&["sensevoice"]),
            default_hint: "sensevoice",
            help: "选择 `[asr]` 的实现；当前只有 SenseVoice（本地离线）。改后需重启。",
            hot: HotReload::RestartOnly,
            required: true,
        }],
    ),
    (
        Capability::Vad,
        &["vad"],
        &[FieldSchema {
            key: "engine",
            label: "VAD 引擎",
            kind: FieldKind::Enum(&["silero"]),
            default_hint: "silero",
            help: "选择 `[vad]` 的实现；当前只有 Silero。改后新会话生效。",
            hot: HotReload::NextSession,
            required: true,
        }],
    ),
    (
        Capability::Tts,
        &["tts"],
        &[
            FieldSchema {
                key: "engine",
                label: "引擎 / 服务商",
                kind: FieldKind::Enum(&["kokoro", "xfyun"]),
                default_hint: "kokoro",
                help: "选择 `[tts]` 的实现（旧值 `sherpa` 仍可读）；保存后新会话生效。",
                hot: HotReload::NextSession,
                required: true,
            },
            FieldSchema {
                key: "cache_entries",
                label: "结果缓存条目数",
                kind: FieldKind::Int,
                default_hint: "256",
                help: "按句缓存已编码下行音频（跨会话共享），命中即免合成延迟；0 = 关闭。",
                hot: HotReload::RestartOnly,
                required: false,
            },
            FieldSchema {
                key: "speed",
                label: "语速",
                kind: FieldKind::Float,
                default_hint: "1.0",
                help: "跨实现参数（`TtsEngine::synthesize_stream` 入参）；1.0 为常速，语音助手不建议 >1.2。",
                hot: HotReload::NextSession,
                required: false,
            },
            FieldSchema {
                key: "speaker",
                label: "发音人 id",
                kind: FieldKind::Int,
                default_hint: "0",
                help: "跨实现的参数槽：Kokoro 用音色 id（测试台可临时覆盖），在线服务商忽略它。",
                hot: HotReload::NextSession,
                required: false,
            },
        ],
    ),
    (
        Capability::Llm,
        &["llm"],
        &[FieldSchema {
            key: "engine",
            label: "LLM 实现",
            kind: FieldKind::Enum(&["openai"]),
            default_hint: "openai",
            help: "选择 `[llm]` 的实现；当前只有 OpenAI 兼容 Responses API。改后新会话生效。",
            hot: HotReload::NextSession,
            required: true,
        }],
    ),
    (
        Capability::FullChain,
        &["aiui"],
        &[FieldSchema {
            key: "enabled",
            label: "启用全链路",
            kind: FieldKind::Bool,
            default_hint: "false",
            help: "启用后本地 ASR/LLM/TTS 全部闲置（云端闭环计费）；需 appid/api_key/api_secret。",
            hot: HotReload::RestartOnly,
            required: true,
        }],
    ),
];

// ---- 字段表（私有段）----

pub(super) const ASR_FIELDS: &[FieldSchema] = &[
    FieldSchema {
        key: "model",
        label: "模型路径",
        kind: FieldKind::Path,
        default_hint: "/data/models/SenseVoiceSmall/model.int8.onnx",
        help: "SenseVoice INT8 模型（sherpa-onnx 离线识别器）。",
        hot: HotReload::RestartOnly,
        required: true,
    },
    FieldSchema {
        key: "tokens",
        label: "词表路径",
        kind: FieldKind::Path,
        default_hint: "/data/models/SenseVoiceSmall/tokens.txt",
        help: "与 model 同目录的 tokens.txt。",
        hot: HotReload::RestartOnly,
        required: true,
    },
    FieldSchema {
        key: "language",
        label: "语言",
        kind: FieldKind::Enum(&["auto", "zh", "en", "ja", "ko", "yue"]),
        default_hint: "auto",
        help: "auto 自动判别（中英混说推荐）。",
        hot: HotReload::RestartOnly,
        required: false,
    },
    FieldSchema {
        key: "use_itn",
        label: "ITN 逆文本规整",
        kind: FieldKind::Bool,
        default_hint: "true",
        help: "把「二零二五年」转成「2025 年」等；关闭则输出原始转写。",
        hot: HotReload::RestartOnly,
        required: false,
    },
    FieldSchema {
        key: "num_threads",
        label: "推理线程数",
        kind: FieldKind::Int,
        default_hint: "2",
        help: "与 TTS 线程数共享 CPU 预算（低功耗主机慎调大）。",
        hot: HotReload::RestartOnly,
        required: false,
    },
    FieldSchema {
        key: "provider",
        label: "执行后端",
        kind: FieldKind::Str,
        default_hint: "cpu",
        help: "sherpa-onnx 执行提供者；当前实现只用 cpu。",
        hot: HotReload::RestartOnly,
        required: false,
    },
];

pub(super) const VAD_FIELDS: &[FieldSchema] = &[
    FieldSchema {
        key: "model",
        label: "Silero 模型路径",
        kind: FieldKind::Path,
        default_hint: "/data/models/silero_vad.onnx",
        help: "为空即视为未配置（sherpa 构建下启动/建会话会报错）。",
        hot: HotReload::NextSession,
        required: true,
    },
    FieldSchema {
        key: "threshold",
        label: "语音判定阈值",
        kind: FieldKind::Float,
        default_hint: "0.5",
        help: "越高越难触发（嘈杂环境可上调；过高会漏掉轻声）。",
        hot: HotReload::NextSession,
        required: false,
    },
    FieldSchema {
        key: "min_silence_duration",
        label: "最短静音时长(s)",
        kind: FieldKind::Float,
        default_hint: "0.25",
        help: "句尾静音超过该时长才切句；调大更不容易把停顿切断。",
        hot: HotReload::NextSession,
        required: false,
    },
    FieldSchema {
        key: "min_speech_duration",
        label: "最短语音时长(s)",
        kind: FieldKind::Float,
        default_hint: "0.25",
        help: "短于该时长的片段丢弃（滤掉咳嗽/噪声）。",
        hot: HotReload::NextSession,
        required: false,
    },
];

pub(super) const TTS_KOKORO_FIELDS: &[FieldSchema] = &[
    FieldSchema {
        key: "model",
        label: "模型路径",
        kind: FieldKind::Path,
        default_hint: "/data/models/Kokoro/model.int8.onnx",
        help: "Kokoro INT8 离线合成模型。",
        hot: HotReload::NextSession,
        required: true,
    },
    FieldSchema {
        key: "voices",
        label: "音色数据",
        kind: FieldKind::Path,
        default_hint: "/data/models/Kokoro/voices.bin",
        help: "与模型同包的 voices.bin。",
        hot: HotReload::NextSession,
        required: true,
    },
    FieldSchema {
        key: "tokens",
        label: "词表路径",
        kind: FieldKind::Path,
        default_hint: "/data/models/Kokoro/tokens.txt",
        help: "与模型同包的 tokens.txt。",
        hot: HotReload::NextSession,
        required: true,
    },
    FieldSchema {
        key: "data_dir",
        label: "espeak-ng 数据目录",
        kind: FieldKind::Dir,
        default_hint: "/data/models/Kokoro/espeak-ng-data",
        help: "音素化数据目录；缺失会导致英文/多语言发音异常。",
        hot: HotReload::NextSession,
        required: true,
    },
    FieldSchema {
        key: "dict_dir",
        label: "jieba 词典目录",
        kind: FieldKind::Dir,
        default_hint: "/data/models/Kokoro/dict",
        help: "中文分词词典（dict 目录）；缺失时中文分词退化。",
        hot: HotReload::NextSession,
        required: false,
    },
    FieldSchema {
        key: "lexicon",
        label: "发音词典",
        kind: FieldKind::Str,
        default_hint: "lexicon-us-en.txt,lexicon-zh.txt",
        help: "逗号分隔的多份词典（中英各一）。",
        hot: HotReload::NextSession,
        required: false,
    },
    FieldSchema {
        key: "lang",
        label: "语言",
        kind: FieldKind::Enum(&["zh", "en"]),
        default_hint: "zh",
        help: "⚠️ 建模时固定，改语言 = 重建引擎（新会话生效，首次约数秒）。",
        hot: HotReload::NextSession,
        required: true,
    },
    FieldSchema {
        key: "num_threads",
        label: "合成线程数",
        kind: FieldKind::Int,
        default_hint: "4",
        help: "单次合成延迟的主要旋钮；调小更保守（与 ASR/VAD 共享 4 核预算）。",
        hot: HotReload::NextSession,
        required: false,
    },
];

pub(super) const TTS_XFYUN_FIELDS: &[FieldSchema] = &[
    FieldSchema {
        key: "app_id",
        label: "app_id",
        kind: FieldKind::Str,
        default_hint: "",
        help: "讯飞开放平台应用 id（与 api_key/api_secret 同属一个应用）。",
        hot: HotReload::NextSession,
        required: true,
    },
    FieldSchema {
        key: "api_key",
        label: "api_key",
        kind: FieldKind::Password,
        default_hint: "",
        help: "密钥只存服务端；管理页不回显明文，留空即保留原值。",
        hot: HotReload::NextSession,
        required: true,
    },
    FieldSchema {
        key: "api_secret",
        label: "api_secret",
        kind: FieldKind::Password,
        default_hint: "",
        help: "密钥只存服务端；管理页不回显明文，留空即保留原值。",
        hot: HotReload::NextSession,
        required: true,
    },
    FieldSchema {
        key: "voice",
        label: "发音人 vcn",
        kind: FieldKind::Str,
        default_hint: "xiaoyan",
        help: "可用音色随账号授权而变；先用「探测音色目录」验证再选。",
        hot: HotReload::NextSession,
        required: true,
    },
];

pub(super) const LLM_OPENAI_FIELDS: &[FieldSchema] = &[
    FieldSchema {
        key: "api_base",
        label: "接口地址",
        kind: FieldKind::Str,
        default_hint: "https://api.example.com/v1/responses",
        help: "OpenAI 兼容 **Responses API** 端点（不是 /chat/completions）。",
        hot: HotReload::NextSession,
        required: true,
    },
    FieldSchema {
        key: "api_key",
        label: "api_key",
        kind: FieldKind::Password,
        default_hint: "",
        help: "密钥只存服务端；管理页不回显明文，留空即保留原值。",
        hot: HotReload::NextSession,
        required: true,
    },
    FieldSchema {
        key: "model",
        label: "模型",
        kind: FieldKind::Str,
        default_hint: "gpt-4o",
        help: "上游模型名；改后新会话生效。",
        hot: HotReload::NextSession,
        required: true,
    },
    FieldSchema {
        key: "system_prompt",
        label: "系统提示词",
        kind: FieldKind::Text,
        default_hint: "你是一个有用且简洁的中文语音助手。",
        help: "语音场景建议短句、少形容词；「灵魂/记忆」接入后会在此之上分层组装。",
        hot: HotReload::NextSession,
        required: false,
    },
    FieldSchema {
        key: "max_history",
        label: "最大历史条数",
        kind: FieldKind::Int,
        default_hint: "10",
        help: "按**条目**截断（一问一答=2 条）；越大越贵、越慢。",
        hot: HotReload::NextSession,
        required: false,
    },
    FieldSchema {
        key: "temperature",
        label: "采样温度",
        kind: FieldKind::Float,
        default_hint: "0.7",
        help: "越低越稳定；语音助手建议 ≤0.8。",
        hot: HotReload::NextSession,
        required: false,
    },
    FieldSchema {
        key: "stream",
        label: "SSE 流式",
        kind: FieldKind::Bool,
        default_hint: "true",
        help: "关闭后退回整段返回（首字延迟明显变差，仅用于不支持 SSE 的端点）。",
        hot: HotReload::NextSession,
        required: false,
    },
];

pub(super) const AIUI_FIELDS: &[FieldSchema] = &[
    FieldSchema {
        key: "appid",
        label: "appid",
        kind: FieldKind::Str,
        default_hint: "",
        help: "AIUI 平台应用 id（enabled=true 时必填，缺一启动即失败）。",
        hot: HotReload::RestartOnly,
        required: true,
    },
    FieldSchema {
        key: "api_key",
        label: "api_key",
        kind: FieldKind::Password,
        default_hint: "",
        help: "密钥只存服务端；管理页不回显明文。",
        hot: HotReload::RestartOnly,
        required: true,
    },
    FieldSchema {
        key: "api_secret",
        label: "api_secret",
        kind: FieldKind::Password,
        default_hint: "",
        help: "密钥只存服务端；管理页不回显明文。",
        hot: HotReload::RestartOnly,
        required: true,
    },
    FieldSchema {
        key: "scene",
        label: "情景模式",
        kind: FieldKind::Enum(&["main_box", "main"]),
        default_hint: "main_box",
        help: "main_box = 平台默认测试情景；生产用平台上实际创建的情景名。",
        hot: HotReload::RestartOnly,
        required: false,
    },
    FieldSchema {
        key: "sn_prefix",
        label: "设备标识前缀",
        kind: FieldKind::Str,
        default_hint: "xiaozhi",
        help: "与设备 MAC 关联，用于云端个性化/上下文绑定。",
        hot: HotReload::RestartOnly,
        required: false,
    },
    FieldSchema {
        key: "voice",
        label: "发音人",
        kind: FieldKind::Str,
        default_hint: "x6_dongmanshaonv_pro",
        help: "极速超拟人目录（x6_*）；不支持的音色会在会话中报错。",
        hot: HotReload::RestartOnly,
        required: false,
    },
    FieldSchema {
        key: "speed",
        label: "语速(0~100)",
        kind: FieldKind::Int,
        default_hint: "50",
        help: "讯飞原生口径，50 为常速。",
        hot: HotReload::RestartOnly,
        required: false,
    },
    FieldSchema {
        key: "volume",
        label: "音量(0~100)",
        kind: FieldKind::Int,
        default_hint: "50",
        help: "讯飞原生口径。",
        hot: HotReload::RestartOnly,
        required: false,
    },
    FieldSchema {
        key: "pitch",
        label: "音调(0~100)",
        kind: FieldKind::Int,
        default_hint: "50",
        help: "讯飞原生口径。",
        hot: HotReload::RestartOnly,
        required: false,
    },
    FieldSchema {
        key: "prompt",
        label: "自定义人设",
        kind: FieldKind::Text,
        default_hint: "",
        help: "对应 nlp.prompt；留空用平台默认人设。",
        hot: HotReload::RestartOnly,
        required: false,
    },
    FieldSchema {
        key: "pace_ms",
        label: "上行分帧间隔(ms)",
        kind: FieldKind::Int,
        default_hint: "10",
        help: "云端流式 VAD 按实时节奏处理：瞬时灌入整段会被判静音（0 = 不等待，不推荐）。",
        hot: HotReload::RestartOnly,
        required: false,
    },
];
